### ISSUE TITLE
Python Update

### ISSUE THREAD

**Issue by GeorgeTMartin** [matlabbe/rtabmap_drone_example#6]
Using python 3.8
rotor_tf script

#!/usr/bin/env python
->
#!/usr/bin/env python3

not sure if it's worth changing in this repo

**Comment by matlabbe** [comment]
Does it cause an issue?

Based on http://wiki.ros.org/UsingPython3/SourceCodeChanges#Changing_shebangs, we should use `#!/usr/bin/env python` to be compatible python2 and python3, however maybe the issue is that we should add this in CMakeLists.txt: 
```cmake
catkin_install_python(PROGRAMS scripts/rotor_tf.py
  DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
```
